name: binary_build

on:
  workflow_dispatch:

jobs:

  build_linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install nuitka
        python -m pip install -r qsensor/requirements.txt
    - name: Build package
      run: |
        cd qsensor
        ./build.sh
        python -m nuitka qsensor.py --standalone --plugin-enable=pyside6 --include-qt-plugins=sensible --assume-yes-for-downloads  --disable-console --linux-icon=assets/icon.png --onefile
    - name: Linux artefact
      uses: actions/upload-artifact@v3
      with:
        name: linux
        path: qsensor/qsensor.bin
